# Generated by Django 4.0.4 on 2022-04-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_regular',
            field=models.BooleanField(default=False, help_text='Designate if staff is regular', verbose_name='regular status'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_special',
            field=models.BooleanField(default=False, help_text='Designate if staff is special', verbose_name='special status'),
        ),
    ]
