# Generated by Django 4.0.4 on 2022-04-27 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_regular_customuser_is_special'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('is_special', 'Special User Status'), ('is_regular', 'Regular User Status')]},
        ),
    ]
