# Generated by Django 4.0.4 on 2022-04-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicmeetings', '0002_alter_meeting_description_alter_meeting_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='description',
            field=models.CharField(help_text='Meeting Description', max_length=255),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='title',
            field=models.CharField(help_text='Meeting Title', max_length=255),
        ),
    ]
