# Generated by Django 4.0.4 on 2022-04-22 08:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academicmeetings', '0004_meeting_publish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['-publish'], 'verbose_name': 'Meeting', 'verbose_name_plural': 'Meetings'},
        ),
        migrations.AlterField(
            model_name='meeting',
            name='publish',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Published Date'),
        ),
    ]
