# Generated by Django 4.0.4 on 2022-04-22 08:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academicmeetings', '0005_alter_meeting_options_alter_meeting_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='publish',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Published Date'),
        ),
    ]
