# Generated by Django 4.0.4 on 2022-04-25 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academicmeetings', '0006_alter_meeting_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='title',
        ),
    ]
