# Generated by Django 4.0.4 on 2022-04-30 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicmeetings', '0008_meeting_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='document',
            field=models.FileField(upload_to='meetings/documents/s/%Y/%m/%d'),
        ),
    ]
