# Generated by Django 4.1.1 on 2022-09-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicmeetings', '0009_alter_meeting_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(blank=True, choices=[('SPECIAL', 'Special'), ('REGULAR', 'Regular')], max_length=20, null=True, verbose_name='Status'),
        ),
    ]
